<?php
namespace app\index\controller;


use think\Controller;

class Index extends Controller
{
    public $redis;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->redis = new \Redis();
        $this->redis->connect('127.0.0.1',6379);
    }

    public function index()
    {
        return $this->fetch();
    }

    //添加数据到队列：
    public function push(){
        if(request()->isAjax()){
            $start = input('post.start');
            $end = input('post.end');
            for($i=$start;$i<=$end;$i++){
                $this->redis->lPush(
                    "myTaskList",$i
                );
            }
            $this->success('数据已添加到Redis队列');
        }
    }

    //模拟浏览量数据到指定的阈值再同步到数据库
    public function updateBrowseCount()
    {
        $id = input('param.id');
        //浏览量Redis中+1
        $add_count = $this->redis->incr("browse:" . $id);
        if($add_count==10){
            //更新到数据库：
            db('browseCount')->where('n_id',$id)->setInc('n_browse_count',10);
            //重新置为0
            $this->redis->set("browse:" . $id,0);
        }
    }
}
